/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "core_cm4.h"
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


uint8_t ui8OnOff = 0; // off

int main(void)
{
	// Enable clock on GPIO and SYSCFG
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;	// Enabled the clock on GPIOC
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODE5_0;

	// GPIO13 is already input (default setting)
	// GPIO3 must enable the pull-up resistor
	GPIOC->PUPDR |= GPIO_PUPDR_PUPD3_0;

	// config SYSCFG to touch the EXTI13 input with PC13
	SYSCFG ->EXTICR[3] |= SYSCFG_EXTICR4_EXTI13_PC;	// linked the PORTC_13 to EXTI Input
	SYSCFG ->EXTICR[0] |= SYSCFG_EXTICR1_EXTI3_PC;	// linked the PORTC_3 to EXTI Input

	// EXTI config. (EXTI15_10)
	EXTI->FTSR |= EXTI_FTSR_TR13;		// selecting the falling edge
	EXTI->PR   |= EXTI_PR_PR13;			// clear the pending registry
	EXTI->IMR  |= EXTI_IMR_IM13;		// enabling the interrupt

	// EXTI config. (EXTI3)
	EXTI->FTSR |= EXTI_FTSR_TR3;		// selecting the falling edge
	EXTI->PR   |= EXTI_PR_PR3;			// clear the pending registry
	EXTI->IMR  |= EXTI_IMR_IM3;			// enabling the interrupt

	// Enable NVIC IRQNo_40 for EXTI15_10
	NVIC ->ISER[1] |= (1U<<8);	// Enabling the IRQ_No40
	// Enable NVIC IRQNo_9 for EXTI3
	NVIC ->ISER[0] |= (1U<<9);	// Enabling the IRQ_No9

	// EXTI3 OnIRQNo=9 PR=5
	//NVIC->IP[9] = (5<<4);


	// disable all int. with pr above 4
	//uint32_t ui32Temp;
	//ui32Temp = (4<<4);
	//__set_BASEPRI(ui32Temp);

	printf("IRQLecture\r\n");

	while(1)
	{
		if(ui8OnOff == 0) GPIOA->BSRR |= GPIO_BSRR_BR5;	// OFF
		if(ui8OnOff == 1) GPIOA->BSRR |= GPIO_BSRR_BS5;	// ON
	}
    /* Loop forever */
	for(;;);
}


void EXTI15_10_IRQHandler(void)
{
	EXTI->PR   |= EXTI_PR_PR13;			// clear the pending registry

	printf("EXTI_15_13 => LED_ON\r\n");
	ui8OnOff = 1;

	//while(1);
	return;
}

void EXTI3_IRQHandler(void)
{
	EXTI->PR   |= EXTI_PR_PR3;

	printf("EXTI_3 => LED OFF\r\n");
	ui8OnOff = 0;

	//while(1);
	return;
}









