/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "core_cm4.h"

void CheckBtn(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


uint8_t uiOnOFF = 0; //OFF

int main(void)
{

	// 1 Enable CLCK GPIOA
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;


	// 2 PA5 from GPIOa as OUTPUT
	GPIOA ->MODER |= GPIO_MODER_MODE5_0;

	// PU on PC3
	//GPIOC->PUPDR |= (1U<<2*3);	// PULL-UP ON PC3

	// 3 toggle on PA5
	//GPIOA->ODR |= GPIO_ODR_OD5;

	uint32_t i;
	while(1)
	{
		if( uiOnOFF )
		{
			//GPIOA->ODR |= GPIO_ODR_OD5;		// PA5 = HIGH
			GPIOA->BSRR = GPIO_BSRR_BS5;
			for(i=0;i<100000; i++)CheckBtn();

			//GPIOA->ODR &= ~GPIO_ODR_OD5;	// PA5 = LOW
			GPIOA->BSRR = GPIO_BSRR_BR5;
			for(i=0;i<100000; i++)CheckBtn();
		}
		else
		{	// OFF

		}

		CheckBtn();
	}
	/* Loop forever */
	for(;;);
}

void CheckBtn(void)
{
	if( !(GPIOC->IDR & (1U<<13)) ) uiOnOFF = 1;	//ON
	if( !(GPIOC->IDR & (1U<<3)) )  uiOnOFF = 0;	//OFF
}
