/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f446xx.h"
#include "core_cm4.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


//#define AHB1ENR 		(*((uint32_t*)0x40023830UL))
#define GPIOA_MODER		(*((uint32_t*)0x40020000UL))
#define GPIOA_ODR		(*((uint32_t*)0x40020014UL))

int main(void)
{
	//RCC: AHB1_ENR:  0x40023830
	//GPIOA MODER:    0x40020000
	//GPIOA ODR       0x40020014

	//AHB1ENR 	|= (0x01U << 0);		// GPIOAEN = ON
	GPIOA_MODER |= (0x01U << 2*5);		// OUTPUT on PA5
	GPIOA_MODER |= (0x01U << 2*6);		// OUTPUT on PA6
	//GPIOA_ODR 	|= (0x01U << 5);		// PA5 = HIGH

	GPIOA->MODER |= (0x01U << 2*5);		// OUTPUT on PA5
	RCC->AHB1ENR |= (0x01U << 0);

	uint32_t i;
	while(1)
	{
		GPIOA_ODR 	|=  (0x01U << 5);		// PA5 = HIGH => ON
		GPIOA_ODR 	&= ~(0x01U << 6);		// PA6 = LOW => OFF
		for(i=0;i<100000; i++);

		GPIOA_ODR 	&= ~(0x01U << 5);		// PA5 = LOW => OFF
		GPIOA_ODR 	|=  (0x01U << 6);		// PA6 = HIGH => ON
		for(i=0;i<100000; i++);
	}

    /* Loop forever */
	for(;;);
}

void EXTI15_10_IRQHandler (void)
{

}
