/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define AHB1ENR  		(*(uint32_t*)0x40023830UL)
#define GPIOA_MODER		(*(uint32_t*)0x40020000UL)
#define GPIOA_ODR		(*(uint32_t*)0x40020014UL)


int main(void)
{
	// RCC  AHB1ENR:   0x40023830
	// GPIOA_MODER:    0x40020000
	// GPIOA_ODR:      0x40020014

	AHB1ENR 		|= (0x01 << 0);		// GPIOAEN = HIGH
	GPIOA_MODER		|= (0x01 << 5*2);	// PA5 = OUTPUT
	GPIOA_MODER		|= (0x01 << 6*2);	// PA6 = OUTPUT
	//GPIOA_ODR 		|= (0x01 << 5);		// PA5 = HIGH

	uint32_t i;
	while(1)
	{
		GPIOA_ODR 		|= (0x01 << 5);		// PA5 = HIGH => ON
		GPIOA_ODR 		&= ~(0x01 << 6);	// PA6 = LOW  => OFF
		for(i=0; i<500000; i++);


		GPIOA_ODR 		&= ~(0x01 << 5);	// PA5 = LOW  => OFF
		GPIOA_ODR 		|= (0x01 << 6);		// PA6 = HIGH => ON
		for(i=0; i<500000; i++);
	}

    /* Loop forever */
	for(;;);
}
